# Generated by Django 5.0.6 on 2024-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_order_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
